# This file is generated, see build.rcl in the repository root.

authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
description = "Support for the RCL configuration language."
id = "rcl"
name = "RCL"
repository = "https://github.com/rcl-lang/zed-rcl"
schema_version = 1
version = "0.7.0"

[grammars]
rcl = { commit = "c7cd31054e54411165acb968091e3e44172cb65c", repository = "https://github.com/rcl-lang/tree-sitter-rcl" }
